package Main;

public enum ProgramState {

    LOGIN,
    MAIN_MENU,
    SHOW_FULL_PRODUCTLIST,
    SHOW_FILTERS,
    SHOW_FILTERED_PRODUCTLIST,
    SHOW_SIZE,
    CHOOSE_SALES_UNIT,
    ADD_TO_CART,
    EXIT,


    R_CUST_BY_PROD,
    R_NUMBER_OF_ORDERS_BY_CUSTOMER,
    R_ORDERED_AMOUNT_BY_CUSTOMER,
    R_ORDERED_AMOUNT_BY_CITY,
    R_TOPLIST_SOLD_QTY_BY_MODEL,

    M_VÄLKOMMEN,
    M_CUSTOMER_LOGIN,
    M_REPORTING



}
